---
title: ""
---
:::{.column-page}
<nav aria-label="Breadcrumb" class="breadcrumb">
  <ol>
    <li><a href="/index.qmd">Home</a></li>
    <li><span aria-current="page">Publications</span></li>
  </ol>
</nav>

# Publications

Below, you'll find a list of my publications. Feel free to also check out my [Google Scholar](https://scholar.google.com/citations?user=wRv_T7sAAAAJ&hl=en){.text-link}, [GitHub](https://github.com/LucasDLalande){.text-link} or [ORCID](https://orcid.org/0000-0001-9319-8033){.text-link} profiles.

If you can't access any of the articles, don't hesitate to [contact me](mailto:lalande.luke@gmail.com){.text-link} to get a copy!

## Published articles

1.  Perez, G., **Lalande, L. D.**, Legros, V., Kodjo, A., Verheyden, H., Bourret, V., Cebe, N., Chaval, Y., Revelli, P., Pellerin, M., Lemaitre, J.-F., Peroz, C., Rey, B., Débias, F., Garcia, R., Bourgoin, G., & Gilot-Fromont, E. (2026). [Possible exposure to unidentified coronaviruses in roe deer (*Capreolus capreolus*) populations suggested by SARS-CoV-2 serological investigation in France](https://doi.org/10.1098/rsos.251477){.text-link}. *Royal Society Open Science*, 13(**1**), 251477.

2.  **Lalande, L. D.**, Bourgoin, G., Carbillet, J., Cheynel, L., Debias, F., Ferté, H., Gaillard, J.-M., Garcia, R., Lemaître, J.-F., Palme, R., Pellerin, M., Peroz, C., Rey, B., Vuarin, P., & Gilot-Fromont, E. (2024). [Early-life glucocorticoids accelerate lymphocyte count senescence in roe deer](https://doi.org/10.1016/j.ygcen.2024.114595){.text-link}. *General and Comparative Endocrinology*, 357, 114595.

3.  **Lalande, L. D.**, Gilot-Fromont, E., Carbillet, J., Débias, F., Duhayer, J., Gaillard, J.-M., Lemaître, J.-F., Palme, R., Pardonnet, S., Pellerin, M., Rey, B., & Vuarin, P. (2023). [Glucocorticoids negatively relate to body mass on the short-term in a free-ranging ungulate](https://doi.org/10.1111/oik.09769){.text-link}. *Oikos*, 2023(**10**), e09769.

4.  **Lalande, L. D.**, Lummaa, V., Aung, H. H., Htut, W., Nyein, U. K., Berger, V., & Briga, M. (2022). [Sex-specific body mass ageing trajectories in adult Asian elephants](https://doi.org/10.1111/jeb.14008){.text-link}. *Journal of Evolutionary Biology*, 35(**5**), 752‑762.

## Ph.D. thesis

**Lalande, L. D.** (2023). [*Stress, Health and Senescence in long-lived mammal, the roe deer (*Capreolus capreolus*)*](https://cnrs.hal.science/tel-04778687){.text-link}. Ph.D. Thesis, Université Claude Bernard - Lyon I.

## Softwares

1.  **Lalande, L. D.** (2026). [*selectools: A facilitating model selection procedure*](https://github.com/LucasDLalande/selectools){.text-link} (Version 0.3.0) \[R package\]. DOI: [10.5281/zenodo.20378446](https://doi.org/10.5281/zenodo.20378446){.text-link}

2.  **Lalande, L. D.** (2026). [*conwaysGoL: An easy-to-handle Conway’s Game of Life simulator for R*](https://github.com/LucasDLalande/conwaysGoL){.text-link} (Version 0.1.1) \[R package\]. DOI: [10.5281/zenodo.18290212](https://doi.org/10.5281/zenodo.18290212){.text-link}
:::